app/simple_pages/models.py
from app.extensions.database import db, CRUDMixin
from datetime import datetime
from flask_login import UserMixin


class User(db.Model, CRUDMixin, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    last_name = db.Column(db.String(80), unique=True)
    first_name = db.Column(db.String(80), unique=True)
    e_mail = db.Column(db.String(150))
    password = db.Column(db.String(1024))
    tasks = db.relationship('Task', backref='user', lazy=True)


class Task(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    time = db.Column(db.Time, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/app.py
from app.extensions.database import db, migrate
from flask import Flask, redirect, url_for, render_template, send_file
from random import randint
from . import simple_pages, authentification
from app.extensions.database import db
from app.extensions.authentication import login_manager


def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config')
    register_extensions(app)
    register_blueprints(app)

    return app


def register_blueprints(app: Flask):
    app.register_blueprint(simple_pages.routes.blueprint)
    app.register_blueprint(authentification.routes.blueprint)


def register_extensions(app: Flask):
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)
    login_manager.init_app(app)

app/authentification/__init__.py
from . import routes

app/authentification/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.simple_pages.models import User
from app.simple_pages.models import Task
from app.extensions.database import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, logout_user, login_user, current_user
from app.extensions.database import CRUDMixin


blueprint = Blueprint('authentification', __name__)


@blueprint.get('/login')
def get_login():
    return render_template('authentification/login.html')


@blueprint.post('/login')
def post_login():
    try:
        user = User.query.filter_by(e_mail=request.form.get('e_mail')).first()

        if not user:
            raise Exception('No user with the given email address was found.')
        elif not check_password_hash(user.password, request.form.get('password')):
            raise Exception('The password does not appear to be correct.')
        login_user(user)
        return redirect(url_for('authentification.dashboard'))

    except Exception as error_message:
        error = error_message or 'An error occurred while logging in. Please verify your email and password.'
        return render_template('authentification/login.html', error=error)


@blueprint.get('/register')
def get_register():
    return render_template('authentification/register.html')


@blueprint.post('/register')
def post_register():
    try:
        if request.form.get('password') != request.form.get('password_confirmation'):
            raise Exception(
                'The password confirmation must match the password.')
        elif User.query.filter_by(e_mail=request.form.get('e_mail')).first():
            raise Exception('The email address is already registered.')

        user = User(
            e_mail=request.form.get('e_mail'),
            password=generate_password_hash(request.form.get('password'))
        )
        user.save()
        login_user(user)
        return redirect(url_for('authentification.dashboard'))
    except Exception as error_message:
        error = error_message or 'An error occurred while creating a user. Please make sure to enter valid data.'
        return render_template('authentification/register.html', error=error)


@blueprint.get('/logout')
def logout():
    logout_user()
    return redirect(url_for('simple_pages.index'))


@blueprint.get('/todo')
@login_required
def dashboard():
    todos = Task.query.filter_by(user_id=current_user.id).all()
    return render_template('authentification/todo.html', todos=todos)


@blueprint.get('/delete/<int:todoid>')
def delete(todoid):
    todo = Task.query.filter_by(id=todoid).first()
    todo.delete()
    return redirect(url_for('authentification.dashboard'))


@blueprint.post('/todo')
def savedtodo():
    name = request.form.get('name')
    date = request.form.get('date')
    time = request.form.get('time')
    date_format = datetime.strptime(date + ' ' + time, '%Y-%m-%d %H:%M')
    date = date_format.date()
    time = date_format.time()
    todo = Task(
        name=name,
        date=date,
        time=time,
        user_id=current_user.id
    )
    todo.save()
    # db.session.add(todo)
    # db.session.commit()
    return redirect(url_for('authentification.dashboard'))


@blueprint.route('/update/<int:todoid>', methods=['GET', 'POST'])
def update(todoid):
    todo = Task.query.filter_by(id=todoid).first()

    if request.method == 'POST':
        todo.name = request.form['name']

        try:
            db.session.commit()
            return redirect('/todo')
        except:
            return 'There was an issue while updating that task'

    else:
        return render_template('authentification/update.html', todo=todo)

app/simple_pages/__init__.py
from . import routes, models

app/simple_pages/routes.py
from .models import User
from flask import Blueprint, render_template, request, current_app

blueprint = Blueprint('simple_pages', __name__)


@blueprint.route('/')
def index():
    return render_template('simple_pages/index.html')


# @blueprint.route('/users')
# def users():
    page_number = request.args.get('page', 1, type=int)
    users_pagination = User.query.paginate(
        page=page_number, per_page=current_app.config['USERS_PER_PAGE'])
    return render_template('simple_pages/users.html', users_pagination=users_pagination)

app/templates/authentification/login.html
{% extends 'base.html' %} {% block title %}TASKBOX - LOGIN{% endblock %} {%
block style %}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/register.css')}}"
/>{% endblock %} {% block body %}
<form method="POST">
  <div class="container">
    <h1>Login</h1>
    <p>Please fill to Login an account.</p>

    <label id="labelpadding" for="e_mail"><b>Email</b></label>
    <input
      type="text"
      placeholder="Enter Email"
      name="e_mail"
      id="e_mail"
      required
    />

    <label for="password"><b>Password</b></label>
    <input
      type="password"
      placeholder="Enter Password"
      name="password"
      id="password"
      required
    />

    <hr />

    <button type="submit" value=":Login">Login</button>
    {% if error %}
    <br />
    <br />
    <p style="color: tomato">{{ error }}</p>
    {% endif %}
  </div>
</form>
{% endblock %}

app/templates/authentification/register.html
{% extends 'base.html' %} {% block title %}TASKBOX - REGISTER{% endblock %} {%
block style %}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/register.css')}}"
/>{% endblock %} {% block body %}
<form method="POST">
  <div class="container">
    <h1>Register</h1>
    <p>Please fill to create an account.</p>

    <label id="labelpadding" for="e_mail"><b>Email</b></label>
    <input
      type="text"
      placeholder="Enter Email"
      name="e_mail"
      id="e_mail"
      required
    />

    <label for="password"><b>Password</b></label>
    <input
      type="password"
      placeholder="Enter Password"
      name="password"
      id="password"
      required
    />

    <label for="password_confirmation"><b>Repeat Password</b></label>
    <input
      type="password"
      placeholder="Repeat Password"
      name="password_confirmation"
      id="password_confirmation"
      required
    />
    <hr />

    <button type="submit" value="Sign Up">Register</button>

    {% if error %}

    <br />
    <br />
    <p style="color: tomato">{{ error }}</p>
    <br />
    {% endif %}
  </div>

  <div class="signin">
    <p>
      Already have an account?
      <a href="{{url_for('authentification.get_login')}}">Sign in</a>.
    </p>
  </div>
</form>
{% endblock %}

app/templates/authentification/todo.html
{% extends 'base.html' %} {% block title %}TASKBOX - TODO{% endblock %} {% block
style %}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/todo.css')}}"
/>{% endblock %}{% block body %}
<button id="hackermode">Hackermode</button>
<div class="paragraph">
  <p>You clicked the Hackermode <span id="countfunc">0</span> Times</p>
</div>
<div class="todo">
  <form method="POST">
    <label for="name">Taskname:</label>
    <input type="text" name="name" id="name" maxlength="20" required />
    <label for="date">Date:</label>
    <input type="date" id="date" name="date" required />
    <label for="time">Time:</label>
    <input type="time" id="time" name="time" required />
    <button id="addtodo" type="submit">add</button>
  </form>

  {% if current_user.is_authenticated %}
  <table>
    <tr>
      <th>Task</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="2">Action</th>
    </tr>
    {% for todo in todos %}
    <tr>
      <td>{{ todo.name }}</td>
      <td>{{ todo.date.strftime('%d.%m.%Y') }}</td>
      <td>{{ todo.time.strftime('%H:%M') }}</td>
      <td>
        <a href="{{url_for('authentification.delete', todoid=todo.id)}}"
          >Delete</a
        >
      </td>
      <td>
        <a href="{{url_for('authentification.update', todoid=todo.id)}}"
          >Update</a
        >
      </td>
    </tr>

    {% endfor %}
  </table>
</div>
{% endif %}
<script>
  let name_mode = "hacker";
  document
    .getElementById("hackermode")
    .addEventListener("click", changetohackermode);
  // document
  // .getElementById("addtodo")
  // .addEventListener("click", checkHackerCookie);

  function changetohackermode() {
    if (name_mode == "hacker") {
      document.body.style.backgroundColor = "#000000";
      const navi = document.querySelector("nav");
      navi.style.border = "5px solid #AAFF00";
      navi.style.color = "#AAFF00";
      const formular = document.querySelector("form");
      formular.style.border = "5px solid #AAFF00";
      formular.style.color = "#AAFF00";
      formular.style.backgroundColor = "#000000";
      const tables = document.querySelector("table");
      tables.style.border = "5px solid #AAFF00";
      tables.style.color = "#AAFF00";
      tables.style.backgroundColor = "#000000";
      const unordered_lists = document.querySelector("ul");
      unordered_lists.style.backgroundColor = "#000000";
      unordered_lists.style.color = "#AAFF00";
      const div_container = document.querySelector(".container");
      div_container.style.backgroundColor = "#000000";
      div_container.style.color = "AAFF00";
      const links = document.querySelector("a");
      links.style.color = "#AAFF00";
      const tabledata = document.querySelectorAll("td, a");
      tabledata.forEach((tabledata) => {
        tabledata.style.backgroundColor = "#000000";
        tabledata.style.color = "#AAFF00";
        tabledata.style.border = "5px solid #AAFF00";
      });

      const inputs = document.querySelectorAll("input, button");
      inputs.forEach((inputs) => {
        inputs.style.backgroundColor = "#000000";
        inputs.style.color = "#AAFF00";
        inputs.style.border = "5px solid #AAFF00";
      });
      const todos = document.querySelector(".todo");
      todos.style.backgroundColor = "#000000";
      todos.style.border = "5px solid #AAFF00";
      const counter = document.querySelector(".paragraph");
      counter.style.border = "5px solid #AAFF00";
      counter.style.color = "#AAFF00";
      counter.style.backgroundColor = "#000000";
    }
  }

  //function setHackerCookie() {
  //const d = new Date();
  //d.setTime(d.getTime() + 24 * 60 * 60 * 1000);
  //let expires = "expires=" + d.toUTCString();
  //document.cookie = "Hacker" + "=" + "true" + ";" + expires + ";path=/";
  //}

  //function getHackerCookie() {
  //let name = "Hacker" + "=";
  //let decodedCookie = decodeURIComponent(document.cookie);
  //let ca = decodedCookie.split(";");
  //for (let i = 0; i < ca.length; i++) {
  //let c = ca[i];
  //while (c.charAt(0) == " ") {
  //c = c.substring(1);
  //}
  //if (c.indexOf(name) == 0) {
  //return c.substring(name.length, c.length);
  //}
  //}
  //return "";
  //}

  //function checkHackerCookie() {
  // let hacker = getHackerCookie();
  //if (hacker != "") {
  //changetohackermode();
  // }
  // }
  //let x = document.cookie;
  //console.log(x);
  var count = 0;
  var button = document.getElementById("hackermode");
  var display = document.getElementById("countfunc");

  button.onclick = function () {
    count++;
    display.innerHTML = count;
  };
</script>
{% endblock %}

app/templates/authentification/update.html
{% extends 'base.html' %} {% block title %}TASKBOX - UPDATE{% endblock %} {%
block style %}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/update.css')}}"
/>{% endblock %}{% block body %}
<div class="todo">
  <h1>Update Task</h1>
  <form
    action="{{url_for('authentification.update', todoid=todo.id)}}"
    method="POST"
  >
    <input type="text" name="name" id="name" value="{{todo.content}}" />
    <input type="submit" value="Update" />
  </form>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
      rel="stylesheet"
    />
    {% block style %} {% endblock %} {% endblock %}
  </head>
  <body>
    {% block nav %}
    <nav>
      <div class="container">
        <h1 class="logo">Taskbox</h1>
        <ul class="navigation">
          {% if not current_user.is_authenticated %}
          <li>
            <a href="{{url_for('simple_pages.index')}}">Home</a>
          </li>
          <li>
            <a href="{{url_for('authentification.get_login')}}">Login</a>
          </li>
          <li>
            <a href="{{url_for('authentification.get_register')}}"
              >Registration</a
            >
          </li>
          {% else %}
          <li>
            <a href="{{ url_for('authentification.logout') }}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% endblock %} {% block body %} {% endblock %}
  </body>
</html>

app/templates/simple_pages/index.html
{% extends 'base.html' %} {% block title %}TASKBOX - HOME{% endblock %} {% block
style %}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/index.css')}}"
/>{% endblock %} {% block body %}

<main>
  <div class="container">
    <img class="image box" src="static/img/toDoListPicture.jpg" alt="" />
    <div class="box">
      <h2>Keep Your Tasks Organized and Get Things Done with Ease</h2>
      <p>
        Say goodbye to sticky notes and messy to-do lists. Our to-do app offers
        a clean and user-friendly interface to help you stay on top of your
        tasks. With our app, you can easily add, edit, and prioritize tasks, set
        due dates and reminders, and track your progress. Whether you need to
        manage work projects, household chores, or personal goals, our app has
        got you covered. Sign up now and start achieving your goals with ease.
      </p>
    </div>
  </div>
  <div class="container2">
    <img class="image box" src="static/img/notes.jpg" alt="" />
    <div class="box">
      <h2>Boost Your Productivity and Focus on What Matters Most</h2>
      <p>
        Are you tired of feeling overwhelmed by your to-do list? Our to-do app
        is designed to help you stay focused and productive. With features like
        task categorization, priority levels, and deadline reminders, you can
        prioritize your tasks and focus on what's important. Our app also offers
        a calendar view to help you plan your schedule and avoid overbooking.
        Whether you're a student, a professional, or a busy parent, our app can
        help you stay organized and achieve your goals. Try it now and take
        control of your day.
      </p>
    </div>
  </div>
</main>
<footer></footer>
{% endblock %}

app/templates/simple_pages/register.html
{% extends 'base.html' %} {% block title %}TASKBOX{% endblock %} {% block style
%}<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/register.css')}}"
/>{% endblock %} {% block body %}
<form action="#">
  <div class="container">
    <h1>Register</h1>
    <p>Please fill to create an account.</p>

    <label id="labelpadding" for="mail"><b>Email</b></label>
    <input
      type="text"
      placeholder="Enter Email"
      name="mail"
      id="mail"
      required
    />

    <label for="pswd"><b>Password</b></label>
    <input
      type="password"
      placeholder="Enter Password"
      name="pswd"
      id="pswd"
      required
    />

    <label for="psw-rpd"><b>Repeat Password</b></label>
    <input
      type="password"
      placeholder="Repeat Password"
      name="psw-rpd"
      id="psw-rpd"
      required
    />
    <hr />

    <button type="submit">Register</button>
  </div>

  <div class="signin">
    <p>
      Already have an account?
      <a href="{{url_for('simple_pages.login')}}">Sign in</a>.
    </p>
  </div>
</form>
{% endblock %}